name: campusconnect
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  firebase_core: ^0.5.2
  flutter_icons: ^1.1.0
  shared_preferences: ^0.5.12+4
  google_sign_in: ^4.5.6
  image_picker: ^0.6.7+14
  firebase_storage: ^5.1.0
  delayed_display: ^1.1.0
  time_formatter: ^1.0.0
  expansion_card: ^0.1.0
  auto_size_text: ^2.1.0
  flutter_spinkit: ^4.1.2+1
  flutter_swiper: ^1.1.6
  date_time_format: ^1.1.0
  url_launcher: ^5.7.10
  photo_view: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
flutter_icons:
  image_path: "icon/icon.png"
  android: false
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - image/google.png
    - image/icon2.png
    - image/sct.png
    - image/cult.png
    - image/cult1.png
    - image/navpage.png
    - image/cc.png
    - image/gg.png
    - image/college.jpg
    - image/no_dp.jpg
    - image/bio.png
    - image/bgimage.jpg
    - image/school1.jpg
    - image/texture2.jpg
    - image/ccbg.png
    - image/197.png


  fonts:
      - family: Marker
        fonts:
          - asset: fonts/PermanentMarker-Regular.ttf
      - family: Raleway
        fonts:
          - asset: fonts/Raleway-Light.ttf
      - family: Nunito
        fonts:
          - asset: fonts/Nunito-Regular.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
